(function () {
  const App = (window.FjordFritert = window.FjordFritert || {});

  App.QUALITY_CLASSES = [
    { min: 0, label: "Vanlig", multiplier: 1.0 },
    { min: 2.4, label: "Fin", multiplier: 1.15 },
    { min: 3.15, label: "Utmerket", multiplier: 1.35 },
    { min: 4.1, label: "Førsteklasses", multiplier: 1.6 },
    { min: 5.05, label: "Mesterfangst", multiplier: 1.95 },
  ];

  App.FISH = {
    mort: {
      id: "mort",
      name: "Mort",
      waterType: "ferskvann",
      rarity: "common",
      basePrice: 14,
      qualityTier: 1,
      minRodLevel: 1,
      weightRangeKg: [0.15, 0.9],
      baseDifficulty: 1,
      preferredBaits: ["mais", "mark"],
      description: "Småblank og vanlig. Perfekt startfisk.",
    },
    abbor: {
      id: "abbor",
      name: "Abbor",
      waterType: "ferskvann",
      rarity: "common",
      basePrice: 18,
      qualityTier: 1,
      minRodLevel: 1,
      weightRangeKg: [0.2, 1.6],
      baseDifficulty: 1.1,
      preferredBaits: ["mark", "spinner"],
      description: "En trofast favoritt i skogsvann og elver.",
    },
    orret: {
      id: "orret",
      name: "Ørret",
      waterType: "ferskvann",
      rarity: "uncommon",
      basePrice: 32,
      qualityTier: 2,
      minRodLevel: 1,
      weightRangeKg: [0.4, 3.8],
      baseDifficulty: 1.6,
      preferredBaits: ["spinner", "mark"],
      description: "Et sikkert trekkplaster på menyen når den er fersk.",
    },
    harr: {
      id: "harr",
      name: "Harr",
      waterType: "ferskvann",
      rarity: "uncommon",
      basePrice: 38,
      qualityTier: 2,
      minRodLevel: 2,
      weightRangeKg: [0.5, 2.2],
      baseDifficulty: 1.7,
      preferredBaits: ["spinner", "mark"],
      description: "Kresen fisk fra elvebredden med pen finne.",
    },
    gjedde: {
      id: "gjedde",
      name: "Gjedde",
      waterType: "ferskvann",
      rarity: "rare",
      basePrice: 55,
      qualityTier: 3,
      minRodLevel: 2,
      weightRangeKg: [1.0, 9.5],
      baseDifficulty: 2.15,
      preferredBaits: ["sluk", "spinner"],
      description: "Rovfisk som gir tunge drag i stanga.",
    },
    roye: {
      id: "roye",
      name: "Røye",
      waterType: "ferskvann",
      rarity: "rare",
      basePrice: 64,
      qualityTier: 3,
      minRodLevel: 2,
      weightRangeKg: [0.8, 4.0],
      baseDifficulty: 2.2,
      preferredBaits: ["spinner", "mark"],
      description: "Klar og kjølig ferskvannsfisk med fin kvalitet.",
    },
    laks: {
      id: "laks",
      name: "Laks",
      waterType: "ferskvann",
      rarity: "epic",
      basePrice: 110,
      qualityTier: 4,
      minRodLevel: 3,
      weightRangeKg: [2.0, 12.0],
      baseDifficulty: 2.9,
      preferredBaits: ["sluk", "spinner"],
      description: "Sjeldnere fangst som virkelig løfter kveldssalget.",
    },
    makrell: {
      id: "makrell",
      name: "Makrell",
      waterType: "saltvann",
      rarity: "common",
      basePrice: 22,
      qualityTier: 2,
      minRodLevel: 2,
      weightRangeKg: [0.25, 1.6],
      baseDifficulty: 1.25,
      preferredBaits: ["sild", "reke"],
      description: "Rask og populær kystfisk som selger jevnt.",
    },
    sei: {
      id: "sei",
      name: "Sei",
      waterType: "saltvann",
      rarity: "common",
      basePrice: 28,
      qualityTier: 2,
      minRodLevel: 2,
      weightRangeKg: [0.5, 4.5],
      baseDifficulty: 1.45,
      preferredBaits: ["sild", "sluk"],
      description: "Effektiv middagsfisk som liker bevegelse.",
    },
    torsk: {
      id: "torsk",
      name: "Torsk",
      waterType: "saltvann",
      rarity: "uncommon",
      basePrice: 42,
      qualityTier: 3,
      minRodLevel: 2,
      weightRangeKg: [0.8, 8.0],
      baseDifficulty: 1.7,
      preferredBaits: ["reke", "sild"],
      description: "En klassiker i fish & chips-kurven.",
    },
    lyr: {
      id: "lyr",
      name: "Lyr",
      waterType: "saltvann",
      rarity: "uncommon",
      basePrice: 48,
      qualityTier: 3,
      minRodLevel: 3,
      weightRangeKg: [1.0, 7.0],
      baseDifficulty: 2.0,
      preferredBaits: ["sluk", "sild"],
      description: "Sterk kampfisk som liker fjordkanten.",
    },
    steinbit: {
      id: "steinbit",
      name: "Steinbit",
      waterType: "saltvann",
      rarity: "rare",
      basePrice: 95,
      qualityTier: 4,
      minRodLevel: 3,
      minBoatLevel: 1,
      weightRangeKg: [2.0, 12.5],
      baseDifficulty: 2.6,
      preferredBaits: ["reke", "sild"],
      description: "Kraftig dypvannsfisk med høy råvareverdi.",
    },
    brosme: {
      id: "brosme",
      name: "Brosme",
      waterType: "saltvann",
      rarity: "rare",
      basePrice: 108,
      qualityTier: 4,
      minRodLevel: 4,
      minBoatLevel: 1,
      weightRangeKg: [2.5, 14.0],
      baseDifficulty: 2.8,
      preferredBaits: ["pilk", "sild"],
      description: "Dyp fjordfisk som krever litt tyngre utstyr.",
    },
    lange: {
      id: "lange",
      name: "Lange",
      waterType: "saltvann",
      rarity: "rare",
      basePrice: 118,
      qualityTier: 4,
      minRodLevel: 4,
      minBoatLevel: 1,
      weightRangeKg: [3.0, 18.0],
      baseDifficulty: 3.0,
      preferredBaits: ["pilk", "sild"],
      description: "Lang og tung fangst som passer dypere områder.",
    },
    uer: {
      id: "uer",
      name: "Uer",
      waterType: "saltvann",
      rarity: "epic",
      basePrice: 150,
      qualityTier: 5,
      minRodLevel: 4,
      minBoatLevel: 2,
      weightRangeKg: [1.5, 7.5],
      baseDifficulty: 3.15,
      preferredBaits: ["pilk", "reke"],
      description: "En flott fangst fra kaldere og dypere vann.",
    },
    breiflabb: {
      id: "breiflabb",
      name: "Breiflabb",
      waterType: "saltvann",
      rarity: "epic",
      basePrice: 210,
      qualityTier: 5,
      minRodLevel: 5,
      minBoatLevel: 2,
      weightRangeKg: [4.0, 20.0],
      baseDifficulty: 3.5,
      preferredBaits: ["sild", "pilk"],
      description: "Eksklusiv fangst som gir et kraftig løft i kassa.",
    },
    kveite: {
      id: "kveite",
      name: "Kveite",
      waterType: "saltvann",
      rarity: "legendary",
      basePrice: 280,
      qualityTier: 5,
      minRodLevel: 5,
      minBoatLevel: 1,
      weightRangeKg: [6.0, 65.0],
      baseDifficulty: 4.0,
      preferredBaits: ["pilk", "sild"],
      description: "Den store drømmen for en ambisiøs fjordfisker.",
    },
  };

  App.getFishById = function getFishById(fishId) {
    return App.FISH[fishId];
  };

  App.getQualityInfo = function getQualityInfo(score) {
    let selected = App.QUALITY_CLASSES[0];
    for (let i = 0; i < App.QUALITY_CLASSES.length; i += 1) {
      if (score >= App.QUALITY_CLASSES[i].min) {
        selected = App.QUALITY_CLASSES[i];
      }
    }
    return selected;
  };
})();
